name: sfit_step_counter
description: A lightweight Flutter package that detects steps in real-time using sensors_plus and provides calories, cadence, geofencing, and walking state.
version: 0.0.18
homepage: https://github.com/dennismuhia/sfit_step_counter

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^6.1.0
  flutter_background: ^1.3.0
  shared_preferences: ^2.5.2
  # geolocator: ^14.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

platforms:
  android:
  ios:
